name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify Executables
        run: chmod +x bin/*.sh
      - name: Run Integrity Check
        run: ./bin/verify-integrity.sh
      - name: Run Status Check
        run: ./bin/status.sh
